version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - '5429:5432'
    networks:
      - infra
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'rust-rest-api'

networks:
  infra:

volumes:
  postgresdb_data:
